apiVersion: batch/v1
kind: Job
metadata:
  name: wise-mplus-evaluator-restore
spec:
  template:
    spec:
      serviceAccountName: default
      securityContext:
        null
      containers:
      - name: wise-mplus-evaluator-restore
        securityContext: {}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
        - name: VCAP_SERVICES
          valueFrom:
            secretKeyRef:
              key: ENSAAS_SERVICES
              name: edge365-secret
        - name: rabbitmq_service_name
          value: p-rabbitmq
        - name: mongodb_service_name
          value: mongodb
        - name: postgresql_service_name
          value: postgresql
        - name: APP_ENV
          value: staging
        - name: JBP_CONFIG_OPEN_JDK_JRE
          value: '[memory_calculator: {stack_threads: 50, memory_sizes: {stack: 512k}}]'
        - name: mplus_version
          value: 2.1.1
        - name: RestoreStartTime
          value: 2024-04-19T16:00:00+0000
        - name: RestoreEndTime
          value: 2024-04-22T16:00:00+0000
        - name: ReCalcGroupIds
          value: '41'
        - name: recalcdevid
          value: '500'
        - name: recalctagname
          value: G_RAE
        - name: debugdevid
          value: '0'
        - name: debugtagname
          value: N_PR
        image: harbor.arfa.wise-paas.com/deviceonbi/wise-mplus-evaluator:dev-2.01.001-Restore.20240509
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "128Mi"
          requests:  
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "128Mi"
      restartPolicy: OnFailure
  backoffLimit: 5
  ttlSecondsAfterFinished: 3600
